In [102]:

import numpy as np # linear algebra
from pandas import DataFrame
from pandas import read_csv
import seaborn as sns # visualization
import matplotlib.pyplot as plt

from sklearn.preprocessing import normalize
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

%matplotlib inline


In [103]:
ls

iris.csv  Iris.ipynb


In [104]:
# load iris database
df = read_csv('iris.csv')
df.columns=['sepal_', 'sepal__', 'petal_', 'petal__', 'type']
types_names=df['type'].unique()
df.head()

sepal_  sepal__  petal_  petal__    type
0     5.1      3.5     1.4      0.2  Setosa
1     4.9      3.0     1.4      0.2  Setosa
2     4.7      3.2     1.3      0.2  Setosa
3     4.6      3.1     1.5      0.2  Setosa
4     5.0      3.6     1.4      0.2  Setosa

In [105]:
# sns.pairplot( data=iris, 
#              vars=iris.columns[:-1])

In [106]:
class Utils:
    
    def simple_encoder(value, series):
        return [index for index , element in enumerate(series.unique()
                                                      ) if str(element)==str(value) ]

    def multy_encoder(values, series):
        array=np.array([Utils.simple_encoder(value=value,
                                             series=df['type']) for value in values])
        array.shape=(len(array),)
        return array
    
    def Relu(series, clf='number_to_str'):
        return series.replace( range(len(types_names)), types_names) if clf=='number_to_str' else series.replace(types_names, range(len(types_names))) 

    
    def normalize(df):
        return df[columns[:-1]].apply(
            lambda series: (series - series.min()
                    ) / (series.max() - series.min()))

In [107]:
df

sepal_  sepal__  petal_  petal__       type
0       5.1      3.5     1.4      0.2     Setosa
1       4.9      3.0     1.4      0.2     Setosa
2       4.7      3.2     1.3      0.2     Setosa
3       4.6      3.1     1.5      0.2     Setosa
4       5.0      3.6     1.4      0.2     Setosa
..      ...      ...     ...      ...        ...
145     6.7      3.0     5.2      2.3  Virginica
146     6.3      2.5     5.0      1.9  Virginica
147     6.5      3.0     5.2      2.0  Virginica
148     6.2      3.4     5.4      2.3  Virginica
149     5.9      3.0     5.1      1.8  Virginica

[150 rows x 5 columns]

In [108]:
df['type']=Utils.multy_encoder(values=df['type'], series=df['type'])

In [109]:
df

sepal_  sepal__  petal_  petal__  type
0       5.1      3.5     1.4      0.2     0
1       4.9      3.0     1.4      0.2     0
2       4.7      3.2     1.3      0.2     0
3       4.6      3.1     1.5      0.2     0
4       5.0      3.6     1.4      0.2     0
..      ...      ...     ...      ...   ...
145     6.7      3.0     5.2      2.3     2
146     6.3      2.5     5.0      1.9     2
147     6.5      3.0     5.2      2.0     2
148     6.2      3.4     5.4      2.3     2
149     5.9      3.0     5.1      1.8     2

[150 rows x 5 columns]

In [110]:
df.describe()

sepal_     sepal__      petal_     petal__        type
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [111]:
series=Utils.Relu(series=df['type'], clf='number_to_str')

In [112]:
series

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: type, Length: 150, dtype: object

In [113]:
df

sepal_  sepal__  petal_  petal__  type
0       5.1      3.5     1.4      0.2     0
1       4.9      3.0     1.4      0.2     0
2       4.7      3.2     1.3      0.2     0
3       4.6      3.1     1.5      0.2     0
4       5.0      3.6     1.4      0.2     0
..      ...      ...     ...      ...   ...
145     6.7      3.0     5.2      2.3     2
146     6.3      2.5     5.0      1.9     2
147     6.5      3.0     5.2      2.0     2
148     6.2      3.4     5.4      2.3     2
149     5.9      3.0     5.1      1.8     2

[150 rows x 5 columns]

In [114]:
x,y=df.iloc[:, :-1],df.iloc[:, -1]

In [115]:
x

sepal_  sepal__  petal_  petal__
0       5.1      3.5     1.4      0.2
1       4.9      3.0     1.4      0.2
2       4.7      3.2     1.3      0.2
3       4.6      3.1     1.5      0.2
4       5.0      3.6     1.4      0.2
..      ...      ...     ...      ...
145     6.7      3.0     5.2      2.3
146     6.3      2.5     5.0      1.9
147     6.5      3.0     5.2      2.0
148     6.2      3.4     5.4      2.3
149     5.9      3.0     5.1      1.8

[150 rows x 4 columns]

In [165]:
scaller=StandardScaler()
x=DataFrame(scaller.fit_transform(x))

In [166]:
x

0         1         2         3
0   -0.900681  1.019004 -1.340227 -1.315444
1   -1.143017 -0.131979 -1.340227 -1.315444
2   -1.385353  0.328414 -1.397064 -1.315444
3   -1.506521  0.098217 -1.283389 -1.315444
4   -1.021849  1.249201 -1.340227 -1.315444
..        ...       ...       ...       ...
145  1.038005 -0.131979  0.819596  1.448832
146  0.553333 -1.282963  0.705921  0.922303
147  0.795669 -0.131979  0.819596  1.053935
148  0.432165  0.788808  0.933271  1.448832
149  0.068662 -0.131979  0.762758  0.790671

[150 rows x 4 columns]

In [167]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=True)

In [168]:
x_train

0         1         2         3
91   0.310998 -0.131979  0.478571  0.264142
135  2.249683 -0.131979  1.331133  1.448832
69  -0.294842 -1.282963  0.080709 -0.130755
128  0.674501 -0.592373  1.046945  1.185567
114 -0.052506 -0.592373  0.762758  1.580464
..        ...       ...       ...       ...
133  0.553333 -0.592373  0.762758  0.395774
137  0.674501  0.098217  0.990108  0.790671
72   0.553333 -1.282963  0.649083  0.395774
140  1.038005  0.098217  1.046945  1.580464
37  -1.143017  1.249201 -1.340227 -1.447076

[120 rows x 4 columns]

In [169]:
y_train

91     1
135    2
69     1
128    2
114    2
      ..
133    2
137    2
72     1
140    2
37     0
Name: type, Length: 120, dtype: int64

In [170]:
model_log=LogisticRegression()

In [178]:
model_log.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [179]:
model_log.coef_

array([[-1.03183336,  1.03993813, -1.77610267, -1.65393917],
       [ 0.65401126, -0.42197508, -0.36041633, -0.75607096],
       [ 0.3778221 , -0.61796305,  2.136519  ,  2.41001014]])

# [120, 4]*[4,3]=[120:3]
# [120:3]*[3,1]=[120:1]

In [180]:
x_train.shape

(120, 4)

In [181]:
process=np.dot(x_train,model_log.coef_.T)

In [182]:
process+model_log.intercept_

array([[-2.02670067,  1.66245116,  0.36424952],
       [-7.50074271,  1.72738708,  5.77335563],
       [-1.23874877,  2.19387767, -0.95512889],
       [-5.41402906,  1.19294694,  4.22108212],
       [-4.8122681 ,  0.52133189,  4.29093621],
       [ 6.39119429,  2.17784735, -8.56904165],
       [-2.12887687,  2.08937543,  0.03950144],
       [ 5.89899726,  2.41049924, -8.3094965 ],
       [-3.22329329,  2.07418309,  1.14911021],
       [-6.05603873,  1.97969383,  4.0763449 ],
       [-5.33439937,  1.33613808,  3.99826128],
       [ 6.04570108,  2.13459351, -8.1802946 ],
       [-4.43830683,  2.17884058,  2.25946625],
       [-4.39647873,  1.3151343 ,  3.08134443],
       [-2.6735047 ,  2.25533749,  0.41816721],
       [-9.26589714,  1.95205519,  7.31384195],
       [ 5.71087464,  2.25719712, -7.96807176],
       [ 6.62782815,  2.05773433, -8.68556249],
       [ 5.22382426,  2.38254455, -7.60636881],
       [-0.91300266,  1.38405264, -0.47104999],
       [ 5.92307321,  2.31076895, -8.233

In [183]:
_process_=np.dot(process,model_log.intercept_)

In [184]:
process

array([[-1.74501426, -0.11310694,  1.8581212 ],
       [-7.2190563 , -0.04817101,  7.26722731],
       [-0.95706236,  0.41831957,  0.53874279],
       [-5.13234264, -0.58261116,  5.7149538 ],
       [-4.53058168, -1.25422621,  5.78480789],
       [ 6.67288071,  0.40228926, -7.07516996],
       [-1.84719045,  0.31381733,  1.53337312],
       [ 6.18068368,  0.63494114, -6.81562482],
       [-2.94160688,  0.29862499,  2.64298189],
       [-5.77435231,  0.20413573,  5.57021658],
       [-5.05271295, -0.43942002,  5.49213297],
       [ 6.3273875 ,  0.35903541, -6.68642291],
       [-4.15662041,  0.40328248,  3.75333794],
       [-4.11479232, -0.4604238 ,  4.57521611],
       [-2.39181828,  0.47977939,  1.91203889],
       [-8.98421072,  0.17649709,  8.80771364],
       [ 5.99256106,  0.48163902, -6.47420008],
       [ 6.90951457,  0.28217624, -7.19169081],
       [ 5.50551068,  0.60698645, -6.11249713],
       [-0.63131624, -0.39150546,  1.0228217 ],
       [ 6.20475962,  0.53521085, -6.739

In [159]:
model_log.intercept_.shape

(3,)

In [130]:
model_log.intercept_

array([-0.28168642,  1.7755581 , -1.49387168])

In [152]:
x_test.shape

(30, 4)

In [135]:
np.dot(x_test,model_log.coef_)+model_log.intercept_

ValueError: shapes (30,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [139]:
model_log.predict(x_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])