In [5]:
import numpy as np
from pandas import DataFrame
from pandas import read_csv
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.model_selection import train_test_split

in_values=np.array([       [0.06363387],
                           [0.89550772],
                           [0.34073466],
                           [0.85228237],
                           [0.96019488],
                           [0.17392543],
                           [0.81905631],
                           [0.31956641],
                           [0.68456833],
                           [0.12627422],
                           [0.82057309],
                           [0.2857397 ],
                           [0.88310743],
                           [0.57810579],
                           [0.73521407],
                           [0.70037147],
                           [0.51923605],
                           [0.58018963],
                           [0.3364865 ],
                           [0.83543872]     ])

out_values=np.multiply(in_values,888)+500

In [6]:




class Back__Propagation:
    def __init__(self,IN=in_values,OUT=out_values, weight=0.01 , bias=0.001, typing=10000, learning_rate=0.0001,stop_moment = 1):
        self.IN=IN
        self.weight=weight
        self.bias=bias
        self.OUT=OUT
        self.predict=self.prediction()
        self.typing = typing
        self.learning_rate=learning_rate
        self.stop_moment=stop_moment
    
    def errors(self):
        return np.sum(((self.predict-self.OUT)**2)/len(self.OUT))
    
    def prediction(self):
        return self.IN*self.weight+self.bias
    
    def update(self):
        
        weight_derivative = -(2) * np.sum((self.IN * (self.OUT-self.predict))/len(self.IN))
        bias_derivative = -(2) * np.sum((self.OUT-self.predict)/len(self.IN))
        self.weight = self.weight - (self.learning_rate * weight_derivative)
        self.bias = self.bias - (self.learning_rate * bias_derivative)
        
    def fuck_you(self):
        print('-')
        print('-')
        print('___________ПОШЕЛ НА ХУЙ !!!___________Со_своим_футболом!!!!!!!!!!!!!' )
        
    def message(self):

        print(self.errors())
        print('YOUR_ERRORS')             
        print('*****************WEIGHT=',self.weight)
        print('*****************BIAS  =',self.bias)

    def skiline_fit(self):
        key=True
        while key:
            if  self.errors()>self.stop_moment:
                that_error=self.errors()
                self.update()
                self.predict=self.prediction()
                this_error=self.errors()
                key=[True if this_error<that_error else False]
                if key:
                    self.message()
                    print('&&&&&&&--------Scanning-------KEY is $$$___', key ) 
            else:
                [self.fuck_you() for _typing_ in range(self.typing)]
                break
                
                
    def ski_fit(self):
        key=True
        while key:
            if  self.errors()>self.stop_moment:
                that_error=self.errors()
                self.update()
                self.predict=self.prediction()
                this_error=self.errors()
                key=[True if this_error<that_error else False]
            else:
                break
        print('TRUE !!!',
             )
    

In [7]:
root=Back__Propagation()

In [8]:
root.ski_fit()

TRUE !!!


In [9]:
root.OUT

array([[ 556.50687656],
       [1295.21085536],
       [ 802.57237808],
       [1256.82674456],
       [1352.65305344],
       [ 654.44578184],
       [1227.32200328],
       [ 783.77497208],
       [1107.89667704],
       [ 612.13150736],
       [1228.66890392],
       [ 753.7368536 ],
       [1284.19939784],
       [1013.35794152],
       [1152.87009416],
       [1121.92986536],
       [ 961.0816124 ],
       [1015.20839144],
       [ 798.800012  ],
       [1241.86958336]])

In [11]:
root.prediction()

array([[ 558.4551398 ],
       [1294.19581305],
       [ 803.53355138],
       [1255.96567983],
       [1351.40758218],
       [ 656.00116389],
       [1226.5792966 ],
       [ 784.81155104],
       [1107.63304417],
       [ 613.85663281],
       [1227.92079416],
       [ 754.89393025],
       [1283.22852791],
       [1013.47355009],
       [1152.42605076],
       [1121.60993846],
       [ 961.40692708],
       [1015.31657695],
       [ 799.77631812],
       [1241.06851917]])

In [ ]:
root.IN

In [6]:
root.prediction()

array([[ 558.4551398 ],
       [1294.19581305],
       [ 803.53355138],
       [1255.96567983],
       [1351.40758218],
       [ 656.00116389],
       [1226.5792966 ],
       [ 784.81155104],
       [1107.63304417],
       [ 613.85663281],
       [1227.92079416],
       [ 754.89393025],
       [1283.22852791],
       [1013.47355009],
       [1152.42605076],
       [1121.60993846],
       [ 961.40692708],
       [1015.31657695],
       [ 799.77631812],
       [1241.06851917]])

In [7]:
root.weight

884.4377945609114