In [163]:
from numpy import array
from numpy import dot
from numpy import exp as exponent
from numpy.random import normal
from math import factorial
from math import log as ln_e
from random import random as random
from pandas import DataFrame
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from matplotlib import pyplot
from time import sleep
from warnings import filterwarnings as message
message('ignore')


# local function

In [164]:
def ReLu(element):
    return True if element>0.5 else False

def gender_switch(gend):
    return 'Male' if gend else 'Female'

def age_generator(diapazone_=19, _diapazone=61):
        random_numbers=[random() for ranger in range(100)]
        _return_=[diapazone_ + (_diapazone-diapazone_)* random_numbers[index] 
                 for index in range(len(random_numbers))]
        return _return_

# N1

In [165]:
elements=[random() for ranger in range(100)]
genders=[ReLu(element) for element in elements ]
_genders_=[gender_switch(gender) for gender in genders]

# N2

In [166]:
ages=age_generator()
ages=[int(age) for age in ages]

# N3

In [167]:
guops=age_generator(200, 10000)
guops=[int(guop) for guop in guops]

In [168]:
def _sigmoid_(element):
    return element/100

In [169]:
def sigmoid(element):
    return exponent(element)/(exponent(element)+1)

In [170]:
def head_skiline(df):
    for index in df.index:
        if df['Genders'][index]:
            df['Sold'][index]+=37
            
            if df['Guops'][index]>7000:
                df['Sold'][index]+=25
                
                if df['Ages'][index]<35:
                    df['Sold'][index]+=33
                    
                elif df['Ages'][index]>40:
                    df['Sold'][index]+=19
                    
                else:
                    df['Sold'][index]+=14

            else:
                if df['Ages'][index]<35:
                    df['Sold'][index]+=33
                    
                elif df['Ages'][index]>40:
                    df['Sold'][index]+=19
                    
                else:
                    df['Sold'][index]+=14
                    
                    
                    
                    
        else:
            if df['Guops'][index]>7000:
                df['Sold'][index]+=18
                
                if df['Ages'][index]<35:
                    df['Sold'][index]+=23
                    
                elif df['Ages'][index]>40:
                    df['Sold'][index]+=16
                    
                else:
                    df['Sold'][index]+=11

            else:
                if df['Ages'][index]<35:
                    df['Sold'][index]+=29
                    
                elif df['Ages'][index]>40:
                    df['Sold'][index]+=18
                    
                else:
                    df['Sold'][index]+=9
    
    df['Sold']=[int(100*_sigmoid_(sold))/100 for sold in df['Sold']]
    return df

In [171]:
df=head_skiline(df)

In [172]:
df

Genders  Ages  Guops  Sold
0     False    59   9368  0.34
1     False    34    280  0.29
2     False    35   9504  0.29
3      True    52   9288  0.81
4     False    52   8913  0.34
..      ...   ...    ...   ...
95     True    27   3975  0.70
96     True    42   7043  0.81
97    False    37   2365  0.09
98     True    32   4880  0.70
99    False    55   9034  0.34

[100 rows x 4 columns]

In [173]:
array([df['Sold'][index] if df['Genders'][index]==False else 'Male' for index in df.index])

array(['0.34', '0.29', '0.29', 'Male', '0.34', '0.29', '0.29', 'Male',
       'Male', 'Male', 'Male', '0.41', 'Male', 'Male', 'Male', 'Male',
       '0.18', 'Male', '0.09', 'Male', '0.18', 'Male', 'Male', 'Male',
       'Male', 'Male', '0.29', 'Male', '0.18', '0.18', 'Male', '0.09',
       '0.41', 'Male', '0.29', 'Male', '0.29', 'Male', 'Male', 'Male',
       'Male', 'Male', '0.18', '0.41', '0.29', 'Male', '0.34', 'Male',
       '0.34', '0.34', '0.34', '0.29', '0.18', 'Male', '0.41', '0.18',
       '0.09', '0.41', '0.41', '0.34', 'Male', '0.18', 'Male', '0.29',
       '0.29', 'Male', '0.29', '0.29', 'Male', '0.29', 'Male', 'Male',
       'Male', 'Male', '0.41', 'Male', 'Male', 'Male', '0.29', 'Male',
       'Male', '0.29', 'Male', '0.29', '0.18', 'Male', '0.29', 'Male',
       'Male', '0.29', '0.41', 'Male', '0.18', '0.09', 'Male', 'Male',
       'Male', '0.09', 'Male', '0.34'], dtype='<U32')

In [174]:
array([df['Sold'][index] if df['Genders'][index] else 'Female' for index in df.index])

array(['Female', 'Female', 'Female', '0.81', 'Female', 'Female', 'Female',
       '0.56', '0.7', '0.81', '0.56', 'Female', '0.56', '0.56', '0.7',
       '0.56', 'Female', '0.56', 'Female', '0.56', 'Female', '0.56',
       '0.81', '0.56', '0.56', '0.7', 'Female', '0.56', 'Female',
       'Female', '0.7', 'Female', 'Female', '0.81', 'Female', '0.51',
       'Female', '0.51', '0.56', '0.7', '0.51', '0.95', 'Female',
       'Female', 'Female', '0.81', 'Female', '0.56', 'Female', 'Female',
       'Female', 'Female', 'Female', '0.95', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', '0.7', 'Female', '0.7', 'Female',
       'Female', '0.81', 'Female', 'Female', '0.56', 'Female', '0.51',
       '0.81', '0.7', '0.7', 'Female', '0.7', '0.95', '0.95', 'Female',
       '0.56', '0.76', 'Female', '0.81', 'Female', 'Female', '0.95',
       'Female', '0.95', '0.81', 'Female', 'Female', '0.95', 'Female',
       'Female', '0.81', '0.7', '0.81', 'Female', '0.7', 'Female'],
      dtype='

In [175]:
X,Y=df.drop('Sold', axis=1),df['Sold']
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.23, random_state=True)

In [176]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [177]:
model.coef_

array([ 4.07237904e-01, -4.37702296e-03,  2.62435938e-05])

In [178]:
model.intercept_

0.32297261023780854

In [179]:
# x_1*w_1 + x_2*w_2, x_3*w_3 + bias = y

In [180]:
model.score(x_test,y_test)

0.8429207086409966

In [181]:
array(y_test)

array([0.76, 0.18, 0.81, 0.29, 0.09, 0.56, 0.29, 0.81, 0.29, 0.81, 0.18,
       0.7 , 0.09, 0.18, 0.29, 0.41, 0.09, 0.29, 0.29, 0.56, 0.29, 0.7 ,
       0.09])

In [182]:
model.predict(x_test)

array([0.77974647, 0.26911651, 0.74205391, 0.3949525 , 0.33600373,
       0.620085  , 0.347024  , 0.76678622, 0.34169089, 0.73708256,
       0.27359332, 0.68435824, 0.19598488, 0.19432635, 0.39824426,
       0.41798667, 0.32734334, 0.26869976, 0.2590781 , 0.58282429,
       0.41919592, 0.77845849, 0.22308886])

In [183]:
Test_values=DataFrame(array(model.predict(x_test)))
y_test.index=range(len(y_test))
Test_values[19]=y_test
Test_values.columns=['Predict', 'Real']
Test_values

Predict  Real
0   0.779746  0.76
1   0.269117  0.18
2   0.742054  0.81
3   0.394952  0.29
4   0.336004  0.09
5   0.620085  0.56
6   0.347024  0.29
7   0.766786  0.81
8   0.341691  0.29
9   0.737083  0.81
10  0.273593  0.18
11  0.684358  0.70
12  0.195985  0.09
13  0.194326  0.18
14  0.398244  0.29
15  0.417987  0.41
16  0.327343  0.09
17  0.268700  0.29
18  0.259078  0.29
19  0.582824  0.56
20  0.419196  0.29
21  0.778458  0.70
22  0.223089  0.09